name: Tests

concurrency:
  group: explicit-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - "**"

jobs:
  explicit_bdd:
    name: Tests
    uses: ./.github/workflows/_tests.yml
    secrets: inherit
    with:
      ref: ${{ github.ref }}